version: '3.8'
services:
  mysql-db:
    image: mysql:9.6.0
    container_name: mysql_reservaciones
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Reservaciones
      MYSQL_USER: admin             
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 2
  # postgresql-db:
  #   image: postgres
  #   container_name: postgres_reservaciones
  #   restart: always
  #   environment:
  #     POSTGRES_DB: Reservaciones
  #     POSTGRES_USER: admin             
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #     - "5439:5432"
  #   volumes:
  #     - postgres_data:/var/lib/

volumes:
  mysql_data:
  # postgres_data: